version: "3.9"
services:
  db:
    container_name: db
    image: postgres:15.0-alpine
    ports:
      - 5433:5432
    restart: always
    volumes: 
      - postgres_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  web:
    container_name: web
    build: .
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_value: