"""initial

Revision ID: 205289e45e0d
Revises: 
Create Date: 2023-05-30 13:29:34.236965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205289e45e0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('zip_code'),
    sa.UniqueConstraint('zip_code')
    )
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('location_zip_code', sa.String(), nullable=False),
    sa.Column('load_capacity', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_zip_code'], ['location.zip_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pick_up_zip_code', sa.String(), nullable=False),
    sa.Column('delivery_zip_code', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_zip_code'], ['location.zip_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pick_up_zip_code'], ['location.zip_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cargo')
    op.drop_table('car')
    op.drop_table('location')
    # ### end Alembic commands ###
