"""initial

Revision ID: 365fea35240b
Revises: 
Create Date: 2023-05-30 11:39:43.995189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365fea35240b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
